# Generated by Django 6.0 on 2025-12-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book entry'), ('can_change_book', 'Can change an existing book entry'), ('can_delete_book', 'Can delete a book entry')]},
        ),
    ]
